#!/usr/bin/env bash

# Show all commands prior to executing them
set -x

# Exit if a command fails
set -e

# The save-artifacts script is responsible for gathering all
# the dependencies into a tar file and streaming it to the 
# standard output (eg. for Ruby - gems installed by Bundler, 
# for Java - .m2 contents, etc.). The existence of this can 
# speed up the following build processes.

echo "Currently we don't have artifacts to save"
